/*
 * Copyright 2022 Martin Zimandl <martin.zimandl@gmail.com>
 * Copyright 2022 Institute of the Czech National Corpus,
 *                Faculty of Arts, Charles University
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { styled } from 'styled-components';

// ---------------- <Preview /> --------------------------------------

export const Preview = styled.div<{maxHeight:number}>`
    position: relative;
    max-height: ${props => props.maxHeight}px;
    overflow: hidden;
`

// ---------------- <Rollover /> --------------------------------------

export const Rollover = styled.div`
    position: absolute;
    height: 5em;
    width: 100%;
    bottom: 0em;
    background: linear-gradient(0deg, rgba(255,255,255,1) 0%, rgba(255,255,255,1) 33%,  rgba(255,255,255,0.7) 66%,  rgba(255,255,255,0.3) 88%, rgba(255,255,255,0) 100%);

    div#hidden-data-label {
        position: absolute;
        bottom: 0em;
        font-size: 1.5em;
        font-weight: 500;
        font-style: italic;
    }
`

// ---------------- <UjcCJATileView /> --------------------------------------

export const UjcCJATileView = styled.div`
    img {
        width: 100%;
    }

    ${Preview} {
        .container {
            color:#333;
            background-color:#fff;
            font-family: zrcola, tahoma, arial, verdana, sans-serif;
            font-size:15px;

            article>header{
                border-bottom:1px solid gainsboro;
                padding-bottom:0.5em;
                margin-bottom:1em
            }
            article>header h1{
                font-size:180%;
                font-weight:200;
                margin:0;
                line-height:1
            }
            article>header span{
                font-size:100%;
                color:#c8c8c8
            }
            article>.row{
                margin:0;
                width:auto
            }
            p.cislooddilu,li.cislooddilu,div.cislooddilu{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black;
                font-weight:bold
            }
            span.cislooddiluChar{
                font-family:"zrcola";
                color:black;
                font-weight:bold
            }
            p.text,li.text,div.text{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.cislostranky-suda,li.cislostranky-suda,div.cislostranky-suda{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:12.0pt;
                font-family:"zrcola";
                color:black
            }
            p.petit,li.petit,div.petit{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddil,li.ctvrtyoddil,div.ctvrtyoddil{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:42.55pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-28.35pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            span.textChar{
                font-family:"zrcola";
                color:black
            }
            span.petitChar{
                font-family:"zrcola";
                color:black
            }
            span.ctvrtyoddilCharChar{
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddil-prvni,li.ctvrtyoddil-prvni,div.ctvrtyoddil-prvni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:42.55pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-42.55pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddil-prvniuvodnitext,li.ctvrtyoddil-prvniuvodnitext,div.ctvrtyoddil-prvniuvodnitext{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-14.2pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddiluvodnitext,li.ctvrtyoddiluvodnitext,div.ctvrtyoddiluvodnitext{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:28.35pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddil-heslo,li.ctvrtyoddil-heslo,div.ctvrtyoddil-heslo{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:42.55pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-42.55pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black;
                font-weight:bold
            }
            span.ctvrtyoddil-prvniCharChar{
                font-family:"zrcola";
                color:black
            }
            span.ctvrtyoddil-hesloChar{
                font-family:"zrcola";
                color:black;
                font-weight:bold
            }
            p.ctvrtyoddil-pokracovanihesla,li.ctvrtyoddil-pokracovanihesla,div.ctvrtyoddil-pokracovanihesla{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:42.55pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddil-posledni,li.ctvrtyoddil-posledni,div.ctvrtyoddil-posledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:42.55pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-28.35pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            span.ctvrtyoddil-posledniCharChar{
                font-family:"zrcola";
                color:black
            }
            p.druhytretioddil,li.druhytretioddil,div.druhytretioddil{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:28.35pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            span.druhytretioddilChar{
                font-family:"zrcola";
                color:black
            }
            p.druhytretioddil-pokracovanitextu,li.druhytretioddil-pokracovanitextu,div.druhytretioddil-pokracovanitextu{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.druhytretioddil-posledni,li.druhytretioddil-posledni,div.druhytretioddil-posledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:28.35pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.druhytretioddil-prvni,li.druhytretioddil-prvni,div.druhytretioddil-prvni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-14.2pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            span.druhytretioddil-prvniChar{
                font-family:"zrcola";
                color:black
            }
            p.autor,li.autor,div.autor{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:24.0pt;
                margin-left:0in;
                text-align:right;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            p.hlavicka,li.hlavicka,div.hlavicka{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                line-height:12.0pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.heslo,li.heslo,div.heslo{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                line-height:12.0pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black;
                font-weight:bold
            }
            span.hlavickaChar{
                font-family:"zrcola";
                color:black
            }
            span.hesloChar{
                font-family:"zrcola";
                color:black;
                font-weight:bold
            }
            p.mapas,li.mapas,div.mapas{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                line-height:12.0pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            span.mapasChar{
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            p.patysestyoddil-prvniaposledni,li.patysestyoddil-prvniaposledni,div.patysestyoddil-prvniaposledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-14.2pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.patysestyoddil-posledni,li.patysestyoddil-posledni,div.patysestyoddil-posledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.patysestyoddil-prvni,li.patysestyoddil-prvni,div.patysestyoddil-prvni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-14.2pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.petit-priklad,li.petit-priklad,div.petit-priklad{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:42.55pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-42.55pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            span.petit-prikladChar{
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            p.petit-PRO,li.petit-PRO,div.petit-PRO{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black;
                text-decoration:underline
            }
            span.petit-PROChar{
                font-family:"zrcola";
                color:black;
                text-decoration:underline
            }
            p.cislostranky-licha,li.cislostranky-licha,div.cislostranky-licha{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:12.0pt;
                font-family:"zrcola";
                color:black
            }
            span.ctvrtyoddil-prvniuvodnitextChar{
                font-family:"zrcola";
                color:black
            }
            span.ctvrtyoddiluvodnitextChar{
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddiluvodnitext-pokracovani,li.ctvrtyoddiluvodnitext-pokracovani,div.ctvrtyoddiluvodnitext-pokracovani{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddiluvodnitext-posledni,li.ctvrtyoddiluvodnitext-posledni,div.ctvrtyoddiluvodnitext-posledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:28.35pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            span.ctvrtyoddiluvodnitext-posledniChar{
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddil-jedensloupec,li.ctvrtyoddil-jedensloupec,div.ctvrtyoddil-jedensloupec{
                margin-top:0in;
                margin-right:241.0pt;
                margin-bottom:0in;
                margin-left:42.55pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-28.35pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            span.ctvrtyoddil-jedensloupecChar{
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddil-jedensloupec-posledni,li.ctvrtyoddil-jedensloupec-posledni,div.ctvrtyoddil-jedensloupec-posledni{
                margin-top:0in;
                margin-right:241.0pt;
                margin-bottom:6.0pt;
                margin-left:42.55pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-28.35pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            span.ctvrtyoddil-pokracovaniheslaChar{
                font-family:"zrcola";
                color:black
            }
            p.ctvrtyoddil-prvniaposledni,li.ctvrtyoddil-prvniaposledni,div.ctvrtyoddil-prvniaposledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:42.55pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-42.55pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.druhytretioddil-pokracovanitextu-posledni,li.druhytretioddil-pokracovanitextu-posledni,div.druhytretioddil-pokracovanitextu-posledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.Stylprvnioddil-prvniMPhoneticSymbols2,li.Stylprvnioddil-prvniMPhoneticSymbols2,div.Stylprvnioddil-prvniMPhoneticSymbols2{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:99.25pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-99.25pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            span.Stylprvnioddil-prvniMPhoneticSymbols2Char{
                font-family:"zrcola";
                color:black
            }
            p.text-priklad,li.text-priklad,div.text-priklad{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            span.text-prikladChar{
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            p.text-prikladzavorka,li.text-prikladzavorka,div.text-prikladzavorka{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-14.2pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            span.text-prikladzavorkaChar{
                font-family:"zrcola";
                color:black
            }
            p.text-PRO,li.text-PRO,div.text-PRO{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:99.25pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-99.25pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black;
                text-decoration:underline
            }
            span.text-PROChar{
                font-family:"zrcola";
                color:black;
                text-decoration:underline
            }
            span.ZkladntextChar{
                color:black
            }
            p.druhytretioddil-prvniaposledni,li.druhytretioddil-prvniaposledni,div.druhytretioddil-prvniaposledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-14.2pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.hlavickaspodheslem,li.hlavickaspodheslem,div.hlavickaspodheslem{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                line-height:12.0pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.hlavicka-podheslo,li.hlavicka-podheslo,div.hlavicka-podheslo{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:28.35pt;
                text-align:justify;
                text-justify:inter-ideograph;
                line-height:12.0pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            span.hlavicka-podhesloChar{
                font-family:"zrcola";
                color:black
            }
            p.petit-prikladzavorka,li.petit-prikladzavorka,div.petit-prikladzavorka{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:42.55pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-42.55pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            span.petit-prikladzavorkaChar{
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            p.podheslo,li.podheslo,div.podheslo{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:28.35pt;
                text-align:justify;
                text-justify:inter-ideograph;
                line-height:12.0pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black;
                font-weight:bold
            }
            span.podhesloChar{
                font-family:"zrcola";
                color:black;
                font-weight:bold
            }
            p.prvnioddil-M,li.prvnioddil-M,div.prvnioddil-M{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:99.25pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-56.7pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-Mdalsi,li.prvnioddil-Mdalsi,div.prvnioddil-Mdalsi{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:99.25pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-85.05pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-Mposledni,li.prvnioddil-Mposledni,div.prvnioddil-Mposledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:99.25pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-56.7pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-Mprvni,li.prvnioddil-Mprvni,div.prvnioddil-Mprvni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:99.25pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-99.25pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-Mprvniaposledni,li.prvnioddil-Mprvniaposledni,div.prvnioddil-Mprvniaposledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:99.25pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-99.25pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-Mvarianta,li.prvnioddil-Mvarianta,div.prvnioddil-Mvarianta{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:99.25pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-28.35pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-Mvarianta-posledni,li.prvnioddil-Mvarianta-posledni,div.prvnioddil-Mvarianta-posledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:99.25pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-28.35pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-N,li.prvnioddil-N,div.prvnioddil-N{
                margin-top:3.0pt;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:42.55pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-28.35pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-SX,li.prvnioddil-SX,div.prvnioddil-SX{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:42.55pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-28.35pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-SXposledni,li.prvnioddil-SXposledni,div.prvnioddil-SXposledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:42.55pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-28.35pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            p.prvnioddil-text,li.prvnioddil-text,div.prvnioddil-text{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            span.prvnioddil-textChar{
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            p.prvnioddil-textpetit,li.prvnioddil-textpetit,div.prvnioddil-textpetit{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            span.prvnioddil-textpetitChar{
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            p.sedmyoddil,li.sedmyoddil,div.sedmyoddil{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:28.35pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.sedmyoddil-posledni,li.sedmyoddil-posledni,div.sedmyoddil-posledni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:28.35pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.sedmyoddil-prvni,li.sedmyoddil-prvni,div.sedmyoddil-prvni{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:0in;
                margin-left:14.2pt;
                margin-bottom:.0001pt;
                text-align:justify;
                text-justify:inter-ideograph;
                text-indent:-14.2pt;
                font-size:8.0pt;
                font-family:"zrcola";
                color:black
            }
            p.upresnenihesla,li.upresnenihesla,div.upresnenihesla{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:14.2pt;
                text-align:justify;
                text-justify:inter-ideograph;
                line-height:12.0pt;
                font-size:10.0pt;
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            span.upresneniheslaChar{
                font-family:"zrcola";
                color:black;
                font-style:italic
            }
            ol{
                margin-bottom:0in
            }
            ul{
                margin-bottom:0in
            }
            span.c6{
                font-family:"zrcola";
                color:black
            }
            span.c5{
                font-size:10.0pt;
                font-family:"zrcola"
            }
            span.c4{
                font-size:10.0pt;
                font-family:"zrcola";
                color:black
            }
            br.c3{
                page-break-before:auto
            }
            span.c2{
                font-family:"zrcola"
            }
            span.c1{
                font-family:"zrcola"
            }
            p.hlavicka-druheheslo-neposledni{
                margin-left:58px;
                font-size:10.0pt
            }
            p.hlavicka-druheheslo{
                margin-left:58px;
                font-size:10.0pt
            }
            p.hlavicka-podheslo{
                margin-left:58px
            }
            p.hlavicka-podhesloneposledni{
                margin-left:58px;
                font-size:8.0pt
            }
            p.nadpismalystredovytucny,li.nadpismalystredovytucny,div.nadpismalystredovytucny{
                margin-top:24.0pt;
                margin-right:0in;
                margin-bottom:12.0pt;
                margin-left:0in;
                text-align:center;
                font-size:12.0pt;
                font-family:"Times New Roman","serif";
                font-weight:bold
            }
            p.prvniodstavec,li.prvniodstavec,div.prvniodstavec{
                margin:0in;
                margin-bottom:.0001pt;
                text-align:justify;
                font-size:10.0pt;
                font-family:"Times New Roman","serif"
            }
            p.predsloupci,li.predsloupci,div.predsloupci{
                margin-top:0in;
                margin-right:0in;
                margin-bottom:6.0pt;
                margin-left:0in;
                text-align:justify;
                text-indent:28.35pt;
                font-size:10.0pt;
                font-family:"Times New Roman","serif"
            }
            span.izoglosaChar{
                font-weight:bold
            }
        }
    }
`;
